### ISSUE TITLE
Database Dump

### ISSUE THREAD

**Issue by bornhaeusser** [dburgmann/cremoria#1]
Hi,

is there a Database dump?

**Comment by dburgmann** [comment]
Hey, this is a very old project - i just transferred it to github from an old svn repository.
I just took a look at my backup drives and unfortunately did not find a database backup.
I actually thought I had a uml of the database structure somewhere, too but didn't find it either.

However you can derive the database structure from the model classes as they are were created using the ORM-Concept if you want to.

**Comment by bornhaeusser** [comment]
no Problem thanks.
